### ISSUE TITLE
Illegal characters in path.

### ISSUE THREAD

**Issue by doggy8088** [obenjiro/vscode-arrr#10]
When I do **Extract Angular Component** and choose the path (Windows), I got an `Illegal characters in path.` error.

![image](https://user-images.githubusercontent.com/88981/93557279-2e51e980-f9ad-11ea-9fe9-3b9fee9425b0.png)

![image](https://user-images.githubusercontent.com/88981/93557297-3c076f00-f9ad-11ea-9494-f6795fa43080.png)

**Comment by obenjiro** [comment]
Should be fixed in v0.1.2 - plz give it a try
