### ISSUE TITLE
Extracing creates *.undefined

### ISSUE THREAD

**Issue by benceHornyak** [obenjiro/vscode-arrr#12]
When I try to extract the following html I get `*.component.undefined` instead of the css/scss.

```html
  <mat-form-field>
    <input
      formControlName="number"
      matInput
      placeholder="Enter a number"
      i18n-placeholder
      type="number"
    />
  </mat-form-field>
```
File structure: 

![Screenshot from 2020-09-23 10-51-17](https://user-images.githubusercontent.com/12515595/93989880-b90a5e00-fd8a-11ea-9264-21ecf3c5aaf0.png)

In the component class the styleUrl is there correctly:

```ts
import { Component, Input } from '@angular/core';

@Component({
    selector: 'app-number-input',
    templateUrl: './number-input.component.html',
    styleUrls: ['./number-input.component.css']
})
export class NumberInputComponent {
    
    constructor () {}
}
```

**Comment by obenjiro** [comment]
Should be fixed in v0.1.2 - plz give it a try
