### ISSUE TITLE
New component creates CSS file by default

### ISSUE THREAD

**Issue by mattcheah** [obenjiro/vscode-arrr#7]
For projects that use SCSS or others, it would be nice for the extension to check the `angular.json` file and see what type of CSS file is being used, and create that type of file instead.

**Comment by ShPelles** [comment]
Duplicate of #5

**Comment by obenjiro** [comment]
Yep. It should be fixed by #5 so it you still can recreate it with v0.1.0 then send me you project structure `tree -L 2` and your angular.json file

**Comment by obenjiro** [comment]
Should be fixed in v0.1.2 - plz give it a try
